### ISSUE TITLE
Bootstrap Editable version

### ISSUE THREAD

**Issue by durdenk** [select2/x-editable#1]
Hi, sorry if this is a stupid issue.
I only include bootstrap editable version of x editable.
bootstrap3-editable/css/bootstrap-editable.css
bootstrap3-editable/js/bootstrap-editable.min.js

And select2 4.0.0 version compatible files are in   src/inputs/select2/lib/ folder,
What I am suppossed to do if I  want to get bootstrap3 version?

**Comment by Gerarddp** [comment]
You need to compile the code, and then the files you need to include are in /dist.

Here's a zip of /dist compiled if you don't want to do it yourself: http://puu.sh/jV2kZ/5cec6422e0.zip

**Comment by durdenk** [comment]
works like a charm, thanks a lot.
Just to remind you, there are js log outputs in your code, I can see them in my browser's console., you may want to remove them sometime.
