### ISSUE TITLE
removed of "input2value"

### ISSUE THREAD

**Issue by BenBezac** [select2/x-editable#4]
Hi,

First of all thx for this update.

Before i see your update i manually changed the function input2value which was returning this.$input.select2('val');  
by 

this.$input.val();

But i see in your commit that you removed it, and my question is why ? Because i need it for my code ( maybe i should stop use it ?)

Thx.

**Comment by pedrofurtado** [comment]
@BenBezac Sorry, the project is not maintained anymore. But feel free to fork the repo and fix what you need 👍
