### ISSUE TITLE
Are you planning to maintain this

### ISSUE THREAD

**Issue by ashgadala** [select2/x-editable#5]
Hi Select2 support. I forked from Vitalets abandoned project and planning to maintain it. All tests written by Vitalets are working fine with bootstrap 4 integration except Select2. Are you planning to maintain this. 

Below is the repo link. if you run the test. you will get an idea on the select2 issues. 

https://github.com/ashgadala/x-editable-Bootstrap4

Thank you so much

**Comment by pedrofurtado** [comment]
@ashgadala Sorry, the project is not maintained anymore. But feel free to fork the repo and fix what you need :+1:
